apiVersion: multitenancy.tenantforge.io/v1alpha1
kind: Tenant
metadata:
  labels:
    app.kubernetes.io/name: operatorzin
    app.kubernetes.io/managed-by: kustomize
  name: tenant-sample
spec:
  clientName: sample-client
  tier: Small
  networkIsolation: Open
  nodePool: true
